version: "3"
services:
  web:
    container_name: DVWS_WEB
    restart: always
    build: .
    ports:
      - 8080:8080 # Websocket
      - 8888:8888 # Frontend
    environment:
      - HEARTBEAT_INTERVAL=30
      - DB_HOST=db
      - DB_USER=dvws
      - DB_PASSWORD=DVWS
      - DB_DATABASE=dvws
    depends_on:
      - db
      
  db:
    image: mysql
    container_name: DVWS_DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecretPassw0rd
      MYSQL_DATABASE: dvws
      MYSQL_USER: dvws
      MYSQL_PASSWORD: DVWS
    volumes:
      - mysql_data:/var/lib/mysql

